server:
  port: 10001

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  prefix: Bearer
  key:
  access:
    expire: 86400000       # 1일 - 1000 * 60 * 60 * 24
    header: Authorization
  refresh:
    expire: 2592000000      # 30 일 - 1000 * 60 * 60 * 24 * 30
    header: RefreshToken

logging:
  pattern:
    console: "[%-5level] %d{yy-MM-dd HH:mm:ss} [%logger{0}:%line] - %msg%n"
  level:
    org:
      springframework: DEBUG